### ISSUE TITLE
AWS::Events::Rule Input for target is not a valid JSON text

### ISSUE THREAD

**Issue by dobeerman** [awsdocs/aws-cloudformation-user-guide#1010]
Hi all,

I have the following resource in my SAM template.yml:

```yaml
MetricsRule:
  Type: AWS::Events::Rule
  Properties:
    Name: MetricsRule
    Description: Puts metrics to the CloudWatch log group
    EventBusName: !FindInMap [LambdaConfig, !Ref stage, eventBusName]
    EventPattern:
      detail:
        status:
          - GENERATED
    State: !FindInMap [LambdaConfig, !Ref stage, eventEnabled]
    Targets:
      - Id: LogGroupTarget
        Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroup}"
        InputTransformer:
          InputPathsMap:
            customer-id: $.detail.customerId
            destination-type: $.detail.destinationType
            provider-id: $.detail.providerId
          InputTemplate: '"cusId = <customer-id> - <destination-type> for <provider-id>"'
```

When I try to deploy this stack it fails with the exception `Input for target LogGroupTarget is not a valid JSON text.`

What I do wrong?

Thanks.
