### ISSUE TITLE
AWS::AppFlow::Flow attribute FlowArn does not exist

### ISSUE THREAD

**Issue by leftiness** [awsdocs/aws-cloudformation-user-guide#1048]
what am I doing

```
[brandon@localhost ~]$ aws cloudformation create-stack --stack-name my-stack --template-body file://example.yaml --parameters ParameterKey=flowname,ParameterValue=my-flow ParameterKey=connname,ParameterValue=my-conn
{
    "StackId": "arn:aws:cloudformation:us-east-2:906288808472:stack/ok-stack/b7771f70-0468-11ec-8e0e-0a07b86d43ba"
}
```

what happens

```
[brandon@localhost ~]$ aws cloudformation describe-stacks --stack-name my-stack | jq -r .Stacks[].StackStatus
ROLLBACK_COMPLETE
[brandon@localhost ~]$ aws cloudformation describe-stack-events --stack-name my-stack | jq -r .StackEvents[].ResourceStatusReason | grep FlowArn
Attribute 'FlowArn' does not exist. Rollback requested by user.
```
what do I expect

* AWS::AppFlow::Flow attribute FlowArn should exist
* StackStatus=CREATE_COMPLETE

workaround

* Remove FlowArn output from example.yaml
* Remove AWS::AppFlow::Flow attribute FlowArn from the documentation

links

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appflow-flow.html
* https://github.com/aws-samples/amazon-appflow/blob/master/appflow-time-automation/appflow.yaml

example.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  flowname:
    Type: String
  connname:
    Type: String
Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn
  FlowArn:
    Value: !GetAtt Flow.FlowArn
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:PutObject
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:ListBucketMultipartUploads
              - s3:GetBucketAcl
              - s3:PutObjectAcl
            Effect: Allow
            Resource:
              - !GetAtt Bucket.Arn
              - !Join
                - ''
                - - !GetAtt Bucket.Arn
                  - /*
            Principal:
              Service: appflow.amazonaws.com
  Flow:
    Type: AWS::AppFlow::Flow
    Properties:
      DestinationFlowConfigList:
        - ConnectorType: S3
          DestinationConnectorProperties:
            S3:
              BucketName: !Ref Bucket
              S3OutputFormatConfig:
                AggregationConfig:
                  AggregationType: None
                FileType: CSV
      FlowName: !Ref flowname
      SourceFlowConfig:
        ConnectorProfileName: !Ref connname
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            Object: Account
      Tasks:
        - TaskType: Filter
          SourceFields:
            - Id
          ConnectorOperator:
            Salesforce: PROJECTION
        - TaskType: Map
          SourceFields:
            - Id
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: Id
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: id
            - Key: SOURCE_DATA_TYPE
              Value: id
      TriggerConfig:
        TriggerType: OnDemand
```
