### ISSUE TITLE
AWS::RDS::GlobalCluster - can't use ARN as SourceDBClusterIdentifier

### ISSUE THREAD

**Issue by bkonicekprivo** [awsdocs/aws-cloudformation-user-guide#1049]
The documentation states that the value of `SourceDBClusterIdentifier` should be "The DB cluster identifier or Amazon Resource Name (ARN) to use as the primary cluster of the global database." (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-globalcluster.html#aws-resource-rds-globalcluster-properties)

My template looks like this:
```
  clusterGlobal:
    Type: AWS::RDS::GlobalCluster
    Properties:
      GlobalClusterIdentifier: !Ref AWS::StackName
      SourceDBClusterIdentifier: !Ref pSourceClusterArn
```

If I set `pSourceClusterArn` to the cluster resource ID, then it deploys successfully. If I instead use the ARN, it fails with the error 
```
Resource handler returned message: "When creating standalone global cluster, value for engineName should be specified
```

For some reason, when using the ARN, it seems to ignore that I set the `SourceDBClusterIdentifier` property at all. The documentation states that if it is set, then you should not set the `Engine` property.
