### ISSUE TITLE
What are the exact password constraints for AWS::RDS::DBInstance?

### ISSUE THREAD

**Issue by specious** [awsdocs/aws-cloudformation-user-guide#1055]
The documentation for `AWS::RDS::DBInstance` specifies master password [constraints](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/c03a45977c5a506e09a22dbe05ff980bec79b805/doc_source/aws-properties-rds-database-instance.md#cfn-rds-dbinstance-masteruserpassword) as:

> The password can include any printable ASCII character except "/", """, or "@".

As I mentioned in aws/aws-sam-cli#3244, a working formulation of this constraint in a stack template seems to be:

```yaml
Parameters:
  DBAdminPassword:
    Description: Database admin password
    Type: String
    MinLength: 8
    MaxLength: 128
    AllowedPattern: "[^\\s@\"\\/]*"
    ConstraintDescription: 'The password can include any printable ASCII character except "/", """, or "@".'
```

However, when creating a new database in the [RDS console](https://console.aws.amazon.com/rds/), the constraints are:

> Constraints: At least 8 printable ASCII characters. Can't contain any of the following: / (slash), '(single quote), "(double quote) and @ (at sign).

When using the deployment tools (e.g. SAM CLI), using any of the characters not recommended by the documentation results in an error:

```
Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 4f707ce0-2889 -408e-a0c0-a82d26d7d241; Proxy: null) 
```

However, using apostrophes seems to work fine this way. 

That means that disallowing single quotes in the password may be  a specific peculiarity of using the web console to create a database. However, it would be useful to gain clarity on the origin of this discrepancy.

So, the questions I'd like to ask are:

- What are the precise character constraints on RDS database passwords
- What is the reason for these constraints
