### ISSUE TITLE
AWS::Config::ConfigurationAggregator - Your request does not specify any regions.

### ISSUE THREAD

**Issue by prerna-p** [awsdocs/aws-cloudformation-user-guide#1114]
According to documentation for [AWS::Config::ConfigurationAggregator](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configurationaggregator.html), specifically the data structure [AccountAggregationSource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configurationaggregator-accountaggregationsource.html) mentions that `AllAwsRegions` and `AwsRegions` are optional properties.  Why does the following template still fail?

```
Description: "This template creates a ConfigurationAggregator for all regions."

Resources:
  CloudFormationConfigurationAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Properties:
      ConfigurationAggregatorName: CloudFormationAggregator
      AccountAggregationSources:
        - AccountIds:
            - !Sub "${AWS::AccountId}"
      Tags:
        - Key: "tagKey"
          Value: "tagValue"
Outputs:
  ResourceId:
    Value: !Ref CloudFormationConfigurationAggregator

```

Error:
```
Resource handler returned message: "Invalid request provided: Your request does not specify any regions. 
Select AWS Config-supported regions and try again. 
(Service: Config, Status Code: 400, Request ID: d5a1ff66-e096-44bb-8aea-743bbad94cc9, Extended Request ID: null)" (RequestToken: 633cb76f-4633-31a3-513e-a095379def44, HandlerErrorCode: InvalidRequest)
```

No errors thrown on using `cfn-lint` either
