### ISSUE TITLE
Documentation for aws-properties-apigatewayv2-stage-routesettings.md is incorrect

### ISSUE THREAD

**Issue by joshhoegen** [awsdocs/aws-cloudformation-user-guide#1220]
[The docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-stage-routesettings.html) mention one data type, but CloudFormation says `{Object}` is needed...

Docs
```
  DataTraceEnabled: Boolean
  DetailedMetricsEnabled: Boolean
  LoggingLevel: String
  ThrottlingBurstLimit: Integer
  ThrottlingRateLimit: Double
```
Our Template
```
LiveStage:
  Type: AWS::ApiGatewayV2::Stage
    Properties:
      AccessLogSettings:
        DestinationArn: !Ref MyArn
        Format: '{ "requestId"  #....JSON formatted stuff
      RouteSettings:
        DataTraceEnabled: true
        DetailedMetricsEnabled: true
        LoggingLevel: INFO
```
:warning: Errors
```
Property validation failure: [Value of property {/RouteSettings/LoggingLevel} does not match type {Object}, Value of property {/RouteSettings/DataTraceEnabled} does not match type {Object}, Value of property {/RouteSettings/DetailedMetricsEnabled} does not match type {Object}]
```
