### ISSUE TITLE
Add tag support for ECS actions

### ISSUE THREAD

**Issue by atkinsonm** [awsdocs/aws-cloudformation-user-guide#209]
`AWS::ECS::Cluster`,  `AWS::ECS::Service`, and `AWS::ECS::TaskDefinition`s should now support `TagResource` and `UntagResource` API actions, but these properties are neither reflected in the documentation nor seem to be supported by CloudFormation yet.

Credit to @robertd for the discovery.

**Comment by nsantiago2719** [comment]
Tried this but it didn't work or am I just doing it in a wrong way? 
```
  FargateService:
    Type: AWS::ECS::Service
    DependsOn: [TaskDefinition]
    Properties:
      ...
      Tags:
         - Key: ServiceName
           Value: 'sample-service'

```
