### ISSUE TITLE
Incorrect YAML in doc_source/aws-resource-ask-skill.md

### ISSUE THREAD

**Issue by reidgould** [awsdocs/aws-cloudformation-user-guide#234]
The YAML in the example on `doc_source/aws-resource-ask-skill.md` is incorrect. `AuthenticationConfiguration` and `VendorId` are shown as nodes under `MySkill` when they should be nodes under `Properties`.

Current, incorrect YAML:
```
MySkill:
  Type: "Alexa::ASK::Skill"   
  Properties:
   SkillPackage:
    S3Bucket: "my-skill-packages"
    S3Key: "skillpackage.zip"
    S3BucketRole: !GetAtt S3BucketReadRole.Arn
    Overrides:
      Manifest:
        apis:
          custom:
            endpoint:
              uri: !GetAtt SkillFunction.Arn
  AuthenticationConfiguration:
    ClientId: "amzn1.application-oa2-client.1234"
    ClientSecret: "1234"
    RefreshToken: "Atzr|1234"
  VendorId: "1234"
```

Corrected YAML:
```
MySkill:
  Type: "Alexa::ASK::Skill"
  Properties:
    SkillPackage:
      S3Bucket: "my-skill-packages"
      S3Key: "skillpackage.zip"
      S3BucketRole: !GetAtt S3BucketReadRole.Arn
      Overrides:
        Manifest:
          apis:
            custom:
              endpoint:
                uri: !GetAtt SkillFunction.Arn
    AuthenticationConfiguration:
      ClientId: "amzn1.application-oa2-client.1234"
      ClientSecret: "1234"
      RefreshToken: "Atzr|1234"
    VendorId: "1234"
```
