### ISSUE TITLE
ElasticSearch zoneAwarenessConfig not available (cannot create 3-zone ES)

### ISSUE THREAD

**Issue by pbudzon** [awsdocs/aws-cloudformation-user-guide#319]
Hi,

`ElasticsearchClusterConfig` property of AWS::Elasticsearch::Domain does not support setting `zoneAwarenessConfig` and CloudFormation seems to assume the `zoneAwarenessConfig. availabilityZoneCount` will be 2 when `ElasticsearchClusterConfig.ZoneAwarenessEnabled` is set to `true`. 
This means a template setting `ElasticsearchClusterConfig.InstanceCount` to 3 and providing 3 subnets (in different AZs) results in the following error:
```
You must choose an even number of data nodes for a two Availability Zone deployment 
```
Which is additionally confusing, since the user is not trying to use 2 zones, but 3.

Example template:
```
AWSTemplateFormatVersion: "2010-09-09"
Description: ElasticSearch resources for logging
Resources:
  ElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: "2012-10-17"
        Statement: # allow account access
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Join ["",  ["arn:aws:es:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId",":domain/*" ] ]
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 100
        VolumeType: gp2
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        DedicatedMasterCount: 3
        DedicatedMasterType: r5.large.elasticsearch
        InstanceCount: 3
        InstanceType: r5.large.elasticsearch
        ZoneAwarenessEnabled: true
      ElasticsearchVersion: 6.5
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      SnapshotOptions:
        AutomatedSnapshotStartHour: 2
      VPCOptions:
        SecurityGroupIds:
          - sg-xxx
        SubnetIds: [ "subnet-aaaa", "subnet-bbb", "subnet-ccc"]
```

Is there a timeline on when CloudFormation will set `ZoneAwarenessConfig` correctly to allow creating 3-zone clusters? Or allow setting it manually at all? Currently adding the properly results in `Encountered unsupported property ZoneAwarenessConfig`.

**If this is expected to take some time, a note in the documentation should inform users not to try to create 3-zone clusters with CloudFormation.**
