### ISSUE TITLE
"Secrets" Parameter of TaskDefintion is not documented in the cloudformation docs for Task Definition 

### ISSUE THREAD

**Issue by smrutiranjantripathy** [awsdocs/aws-cloudformation-user-guide#364]
Hi Team,
The "Secrets" parameter which is supported in containerdefinition of ECS is also supported in cloudformation. But it is missing from the cloudformation documentation of task definition.

Link of Supported ECS "Secrets" Parameter under Environment section of this document :
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

Link of Cloudformation doc for Containerdefinition: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

Github link for the same: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-ecs-taskdefinition-containerdefinitions.md

I have tested and the secrets parameter works fine with cloudformation:
Below is the template for the same:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: busybox
          Image: httpd
          Secrets:
            - Name: secman
              ValueFrom: 'arn:aws:ssm:us-east-1:<account-id>:parameter/database_password.'
          Memory: '128'
          Essential: 'true'
      ExecutionRoleArn: 'arn:aws:iam::<account-id>:role/ecsTaskExecutionRole'

```
