### ISSUE TITLE
Stack cost estimation calculator pre-population missing some resources

### ISSUE THREAD

**Issue by PatMyron** [awsdocs/aws-cloudformation-user-guide#368]
Is this snippet about pre-populating with the template limited to certain resource types?

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/27492f6ecad0416589adc0ecbc5b0a7d60dbae43/doc_source/using-cfn-paying.md#L12

I'm able to see pre-population for some resources like `EC2` and `RDS` instances, but I'm not able to see pre-population for this `DynamoDB` template:

```
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "ArtistId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ArtistId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 999
        WriteCapacityUnits: 999
```
