### ISSUE TITLE
Incorrect Tag Type for AWS::SSM:Parameter resource. It should be Map Type

### ISSUE THREAD

**Issue by lagrianitis** [awsdocs/aws-cloudformation-user-guide#513]
In the https://raw.githubusercontent.com/awsdocs/aws-cloudformation-user-guide/master/doc_source/aws-resource-ssm-parameter.md
it describes: 

```
`Tags`  <a name="cfn-ssm-parameter-tags"></a>
An array of key\-value pairs to apply to this resource\.  
For more information, see [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html)\.  
*Required*: No  
*Type*: Json  
*Update requires*: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
```

If we try to deploy a CFN template with this content:

```yaml
  # SSM Parameter that stores the CodeCommit repository name
  CodeCommitSsmParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tags:
      - Key: 'MY_KEY'
        Value: 'MY_VALUE'
      Name: '/my-param-key'
      Value: '/my-param-value'
      Type: String
```

Cloudformation will fail with error: 
```
AWS::SSM::Parameter Property validation failure: [Value of property {/Tags} does not match type {Map}]
```

The documentation section needs to be updated and change the type from `JSON` to `Map` for Tags.
It should have this form:
```
Tags:
  MY_KEY1: MY_VALUE
  MY_KEY2: MY_VALUE2
```
