### ISSUE TITLE
Property "Tags" should be remove from AWS::SSM::Document doc

### ISSUE THREAD

**Issue by lktslionel** [awsdocs/aws-cloudformation-user-guide#519]
#### SUMMARY

The [doc syntax of the resource AWS::SSM::Document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html#cfn-ssm-document-tags) must NOT mention the property `Tags`.

In fact, creating a resource with the `Tags` fails with an `Invalid template resource property 'Tags'` error.

#### ISSUE TYPE

* Fix doc

#### RESOURCE NAME

AWS::SSM::Document

#### STEPS TO REPRODUCE

1. Create a simple  CFN template

```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: xxx
Resources:
  SSMDoc1:
    Type: "AWS::SSM::Document"
    Properties:
      ...
    Tags:
      - Key: "Env"
        Value: "dev"
```

2. Deploy the template

```bash
aws cloudformation deploy \
      --capabilities CAPABILITY_IAM \
      --no-fail-on-empty-changeset --template /path/to/template \
      --stack-name doc1-stack
```

#### EXPECTED RESULTS

Stack `doc1-stack` created with resource `SSMDoc1` in cloudformation console.

#### ACTUAL RESULTS

```bash
Failed to update stack rzo-dev-ops-commands: <class 'Exception'>: An error occurred (ValidationError) when calling the UpdateStack operation: Invalid template resource property 'Tags'"
```

#### SYSTEM CONFIGURATION

| Item | Version| 
|------|--------|
|aws-cli|1.16.268|
|Python|3.7.4|
|Darwin|18.7.0|
|botocore|1.13.4|
|OS|Mac OS X/10.14.6|
