### ISSUE TITLE
Tag has an example containing error 

### ISSUE THREAD

**Issue by TheWesDias** [awsdocs/aws-cloudformation-user-guide#690]
#### Using the yaml example on the following url
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
#### Instead of
```yaml
Tags: 
  - 
    Key: "keyname1"
    Value: "value1"
  - 
    Key: "keyname2"
    Value: "value2"
```
#### We have to use
```yaml
Tags: 
  - Key: "keyname1"
    Value: "value1"
  - Key: "keyname2"
    Value: "value2"
```
