### ISSUE TITLE
Discrepancy with documentation for AWS::SSM::MaintenanceWindowTask Target

### ISSUE THREAD

**Issue by JohnZProd** [awsdocs/aws-cloudformation-user-guide#728]
Discrepancy with documentation for `AWS::SSM::MaintenanceWindowTask` property `Targets` (Type: List of `Target`)

Targets
   -The targets, either instances or window target IDs.

However, in the documentation for the Target object type

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-ssm-maintenancewindowtask-target.md

`Pattern: ^[\p{L}\p{Z}\p{N}_.:/=\-@]*$|resource-groups:ResourceTypeFilters|resource-groups:Name`

This has led some users to believe they can directly specify a resource group (by name) in the Targets property of a AWS::SSM::MaintenanceWindowTask resource

For example, this does not work:
```
Resources:
  PatchTask:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Description: Apply OS patches on instances in target
      MaxConcurrency: 1
      MaxErrors: 1
      Priority: 0
      TaskType: RUN_COMMAND
      WindowId:
        Ref: MaintenanceWindow
      TaskArn: AWS-RunPatchBaseline
      Targets:
        - Key: resource-groups:Name
          Values:
            - "TestResourceGroup"

  MaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      Name: MaintenanceWindow
      AllowUnassociatedTargets: true
      Cutoff: 0
      Description: Maintenance window for instances
      Duration: 1
      Schedule: cron(20 17 ? * MON-FRI *)
```
This will result in a CREATE_FAILED with the message 

`resource-groups:Name is an invalid window task target type, use WindowTargetIds or InstanceIds`

However, specifying the resource group as a AWS::SSM::MaintenanceWindowTarget type, and using the MaintenanceWindowTarget's !Ref ID as the target for the AWS::SSM::MaintenanceWindowTask resource WILL WORK

```
Resources:
  PatchTask:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Description: Apply OS patches on instances in target
      MaxConcurrency: 1
      MaxErrors: 1
      Priority: 0
      TaskType: RUN_COMMAND
      WindowId:
        Ref: MaintenanceWindow
      TaskArn: AWS-RunPatchBaseline
      Targets:
        - Key: WindowTargetIds
          Values:
            - Ref: MaintenanceWindowTarget

  MaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      Name: MaintenanceWindow
      AllowUnassociatedTargets: true
      Cutoff: 0
      Description: Maintenance window for instances
      Duration: 1
      Schedule: cron(20 17 ? * MON-FRI *)

  MaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties: 
      ResourceType: RESOURCE_GROUP
      Targets:
        - Key: resource-groups:Name
          Values:
            - "TestResourceGroup"
      WindowId: 
        Ref: MaintenanceWindow
```
Suggest that the 'Pattern' be fixed on - https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-ssm-maintenancewindowtask-target.md, such that users know that a AWS::SSM::MaintenanceWindowTarget is required when the Task target is a resource group.

Alternatively, implement the ability for users to DIRECTLY specify a resource group as a target in the AWS::SSM::MaintenanceWindowTask resource
