### ISSUE TITLE
Encountered unsupported properties in LustreConfiguration: AutoImportPolicyType

### ISSUE THREAD

**Issue by jdrake** [awsdocs/aws-cloudformation-user-guide#762]
The docs say that AutoImportPolicyType is supported, but CloudFormation errors with:
```
Property validation failure: [Encountered unsupported properties in {/LustreConfiguration}: [AutoImportPolicyType]]
```
My resource definition is:
```yaml
LustreFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      StorageCapacity: 1200
      SubnetIds: ...
      SecurityGroupIds: [!Ref LustreFilesystemSecurityGroup]
      LustreConfiguration:
        # AutoImport is on. Amazon FSx automatically imports directory listings of any
        # new objects added to the linked S3 bucket that do not currently exist in the
        # FSx file system.
        AutoImportPolicyType: NEW
        AutomaticBackupRetentionDays: !Ref AutomaticBackupRetentionDays
        CopyTagsToBackups: true
        # Daily at midnight
        DailyAutomaticBackupStartTime: "00:00"
        DeploymentType: PERSISTENT_1
        ImportPath: !Sub
          - s3://${BucketName}
          - BucketName: ...
        PerUnitStorageThroughput: 200
        WeeklyMaintenanceStartTime: "7:02:00"
```
