### ISSUE TITLE
Incorrect formatting of example YAML under heading "Convert Record Format" on "AWS::KinesisFirehose::DeliveryStream" page

### ISSUE THREAD

**Issue by abk7777** [awsdocs/aws-cloudformation-user-guide#803]
The yaml showing an example of record format conversion is badly formatted.

It currently looks like this:
```
AWSTemplateFormatVersion: 2010-09-09 Description: Stack for
            Firehose DeliveryStream S3 Destination. Resources: GlueDatabase: Type:
            AWS::Glue::Database Properties: CatalogId: !Ref AWS::AccountId DatabaseInput: {}
            GlueTable: Type: AWS::Glue::Table Properties: CatalogId: !Ref AWS::AccountId
            DatabaseName: !Ref GlueDatabase TableInput: Owner: owner Retention: 0
...
```

It should look something like this:
```
AWSTemplateFormatVersion: 2010-09-09 
Description: Stack for Firehose DeliveryStream S3 Destination. 
Resources: 
  GlueDatabase: 
    Type: AWS::Glue::Database 
    Properties: 
      CatalogId: !Ref AWS::AccountId 
      DatabaseInput: {}
  GlueTable: 
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase 
      TableInput: 
        Owner: owner 
        Retention: 0
...
```

The JSON & YML examples under the "Create a Kinesis Data Firehose Delivery Stream" heading also contain bad formatting. I will submit a pull request for this soon.
