### ISSUE TITLE
CompositeAlarm requires previous alarms to exist

### ISSUE THREAD

**Issue by furstenheim** [awsdocs/aws-cloudformation-user-guide#911]
Hi,
I have a CFN that creates two alarms and a composite alarm depending on those two.

```
FirstAlarm:
   Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "FirstAlarm"
      ....
 SecondAlarm:
   Type: "AWS::CloudWatch::Alarm"
   Properties:
       AlarmName: "SecondAlarm"
  CompositeAlarm:
    Type: "AWS::CloudWatch::CompositeAlarm"
    Properties:
      AlarmName: "CompositeAlarm"
      AlarmRule: (ALARM(FirstAlarm) OR ALARM(SecondAlarm))
   DependsOn:
     - FirstAlarm
     - SecondAlarm
```
When I execute the changeset it fails on CompositeAlarm because "Could not save the composite alarm as alarms ... in the alarm rule do not exist".

However, if I do two deployments, one with FirstAlarm and SecondAlarm, and a second deployment with the three of them, then it works.

In my opinion this is an error in cfn, but I'm not sure where to report it. At least it should appear on the documentation, that's why I'm opening this issue.

In spirit it is a similar issue to [this one](https://github.com/aws/serverless-application-model/issues/313)
