### ISSUE TITLE
Glue Encountered unsupported properties in EncryptionConfiguration i.e S3Encryption

### ISSUE THREAD

**Issue by apikodes** [awsdocs/aws-cloudformation-user-guide#919]
When using CF template to create GlueSecurityConfiguration
```yaml
  GlueSecurityConfiguration:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: 'GlueSecurityConfiguration'
      EncryptionConfiguration:
        S3Encryption:
          - S3EncryptionMode: SSE-KMS
            KmsKeyArn: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3'
```
Getting Below Error from CloudFormation Stack Creation Event:
```
Property validation failure: [Encountered unsupported properties in {/EncryptionConfiguration}: [S3Encryption]]
```
- If above property is not supported, can this be made clear on this Documentation Page.
`https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-glue-securityconfiguration-s3encryption.md`

**Comment by apikodes** [comment]
@osiro Below can be used.
```yaml
# AWS Glue Security Configuration for Encryption
   GlueSecurityConfiguration:
     Type: AWS::Glue::SecurityConfiguration
     Properties:
       Name: 'my-glue-sec-conf'
       EncryptionConfiguration:
         S3Encryptions:
           - S3EncryptionMode: SSE-KMS
             KmsKeyArn: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3'

```
