### ISSUE TITLE
AWS::EMR::SecurityConfiguration : CloudFormation cannot update a stack when a custom-named resource requires replacing

### ISSUE THREAD

**Issue by apikodes** [awsdocs/aws-cloudformation-user-guide#927]
Created EMR Security Configurationsing below Code:
```yaml
  EMRSecurityConfiguration:
    Type: AWS::EMR::SecurityConfiguration
    Properties:
      Name: !Sub '${Environment}_emr_cluster_security_configuration'
      SecurityConfiguration:
        EncryptionConfiguration:
          EnableAtRestEncryption: true
          AtRestEncryptionConfiguration:
            S3EncryptionConfiguration:
              EncryptionMode: SSE-S3
           EnableInTransitEncryption: false
``` 
- The above YAML code in CF Stack created the EMR Security Configuration with name `dev_emr_cluster_security_configuration`.
- After adding below code in the existing CF Resource, CF Stack Update gives the following error: `CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename dev_emr_cluster_security_configuration and update the stack again`
- 
```yaml
  EMRSecurityConfiguration:
    Type: AWS::EMR::SecurityConfiguration
    Properties:
      Name: !Sub '${Environment}_emr_cluster_security_configuration'
      SecurityConfiguration:
        EncryptionConfiguration:
          EnableAtRestEncryption: true
          AtRestEncryptionConfiguration:
            LocalDiskEncryptionConfiguration:
              AwsKmsKey: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ebs'
              EncryptionKeyProviderType: AwsKms
            S3EncryptionConfiguration:
              EncryptionMode: SSE-S3
           EnableInTransitEncryption: false
```

- Can this be more clarified?
- Why is CloudFormation considering EMR Security Configuration as a Custom Name Resource ?
