### ISSUE TITLE
RDS OptionGroup OptionConfigurations is not required

### ISSUE THREAD

**Issue by pplu** [awsdocs/aws-cloudformation-user-guide#934]
Hi,

   In https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html#cfn-rds-optiongroup-optionconfigurations, OptionConfigurations is marked as required. This is not true, since:

```
  DatabaseOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      OptionGroupDescription: 'Description'
      EngineName: mysql
      MajorEngineVersion: "5.6"
```
is accepted by CloudFormation.

I've fixed this by applying this patch to CloudFormation spec:

```
diff --git a/spec/spec.json b/spec/spec.json
index 3dc729b..30e0d69 100644
--- a/spec/spec.json
+++ b/spec/spec.json
@@ -75771,7 +75771,7 @@
                "Documentation" : "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html#cfn-rds-optiongroup-optionconfigurations",
                "DuplicatesAllowed" : true,
                "ItemType" : "OptionConfiguration",
-               "Required" : true,
+               "Required" : false,
                "Type" : "List",
                "UpdateType" : "Immutable"
             },
```
