### ISSUE TITLE
Documentation indicates AWS::ECR::PublicRepository is supported in Cloudformation, but it isn't

### ISSUE THREAD

**Issue by allycoops80** [awsdocs/aws-cloudformation-user-guide#956]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-ecr-publicrepository.md

Would indicate that Cloudformation supports Public ECR repositories, but the cloudformation validator rejects AWS::ECR::PublicRepository as being an unrecognized resource type.

The API is there, e.g. `aws ecr-public create-repository` works from CLI so it's not clear if this is a documentation issue or a cloudformation validator issue.

**Comment by rachfop** [comment]
The CloudFormation designer didn't give me any issues when I ran this template through and the PublicRepository deployed for me:
```
Resources:
  MyPublicRepositry:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: "test-repository"
      RepositoryCatalogData:
        UsageText: "This is a sample usage text."
        AboutText: "This is a sample about text."
        OperatingSystems:
          - "Linux"
          - "Windows"
        Architectures:
          - "x86"
          - "ARM"
        RepositoryDescription: "This is a sample repository description."
```
But [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint) did say, "Invalid or unsupported Type AWS::ECR::PublicRepository for resource MyPublicRepositry in us-east-1".
Can you confirm which validator you were using?
