### ISSUE TITLE
Error deploying Appstream Stack in cloudformation -- "DOMAIN_PASSWORD_SIGNIN" and "DOMAIN_SMART_CARD_SIGNIN"

### ISSUE THREAD

**Issue by jorenknieper** [awsdocs/aws-cloudformation-user-guide#962]
Hi 

I'm currently experiencing an error defining 2 permissions for an appstream stack in cloudformation. It seems that I cannot add  "DOMAIN_PASSWORD_SIGNIN" and "DOMAIN_SMART_CARD_SIGNIN" actions. 

The code I used in the cloudformation template is: 

```
      UserSettings:
        - Action: 'CLIPBOARD_COPY_FROM_LOCAL_DEVICE'
           Permission: ENABLED
        - Action: 'CLIPBOARD_COPY_TO_LOCAL_DEVICE'
           Permission: ENABLED
        - Action: 'FILE_DOWNLOAD'
           Permission: ENABLED          
        - Action: 'FILE_UPLOAD'
           Permission: ENABLED
        - Action: 'PRINTING_TO_LOCAL_DEVICE'
           Permission: ENABLED 
        - Action: 'DOMAIN_PASSWORD_SIGNIN'
           Permission: ENABLED 
        - Action: 'DOMAIN_SMART_CARD_SIGNIN'
           Permission: DISABLED
```

And I'm receiving the error: 
`Property validation failure: [Value for property {/UserSettings/5/Action} does not match pattern {^CLIPBOARD_COPY_FROM_LOCAL_DEVICE$|^CLIPBOARD_COPY_TO_LOCAL_DEVICE$|^FILE_UPLOAD$|^FILE_DOWNLOAD$|^PRINTING_TO_LOCAL_DEVICE$}]`

When I ran the cloudformation template without the 'DOMAIN_PASSWORD_SIGNIN' and 'DOMAIN_SMART_CARD_SIGNIN'
action, the template completed. 

I looked at the documentation in GitHub but it seems that this has been added recently. Is there a possibility that this is not supported yet in EU-WEST-1?
https://github.com/awsdocs/aws-cloudformation-user-guide/commit/a8b833b819145e06ede952fc876c0d794a303ce6#diff-2853ca5c72f04858cf82feefe6213dddfbcc6b2f1ef55798238c83dbbd13f5cb

Kind regards,
Joren
