### ISSUE TITLE
AWS::EC2::TransitGatewayMulticastDomain documentation is inadequate 

### ISSUE THREAD

**Issue by jp-xbox-gaming** [awsdocs/aws-cloudformation-user-guide#981]
Currently [available documentation](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-ec2-transitgatewaymulticastdomain.md) for TransitGateway MulticastDomain is inadequate.

Multicast Domain created by following this documentation is unusable as it creates the domain with both IGMP as well as Static supports disabled.

The `Options` property and all it's sub-properties are missing from documentation. Given below is YAML example that shows this property.

```
TransitGatewayMulticastDomain:
  Type: AWS::EC2::TransitGatewayMulticastDomain
  Properties:
    TransitGatewayId: !Ref TransitGatewayId
    Options:
      Igmpv2Support: enable
      StaticSourcesSupport: disable
      AutoAcceptSharedAssociations: enable
```
